# Generated by Django 4.1.6 on 2023-02-09 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('profile_id', models.IntegerField(unique=True)),
                ('likes', models.IntegerField()),
                ('foto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('ref_descricao', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'referencia',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(default='blank-profile-picutre.jpg', upload_to='profile_images')),
                ('seguidores', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.post')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.referencia'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField()),
                ('comment_text', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.post')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
