# Generated by Django 4.1.6 on 2023-02-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seguidores',
            field=models.IntegerField(default=0),
        ),
    ]
